version: '3.11'

services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      DB_ENGINE: mysql
      DB_DATABASE: moneyapp
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: moneyapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
    volumes:
      - app/opentelemetry.config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]

volumes:
  db: {}